// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhDRQLB0F7V3AW8UCfY8jVSYOiy5jZgs',
    appId: '1:61999112245:android:dd97c8737e65000831117c',
    messagingSenderId: '61999112245',
    projectId: 'g4metalab',
    databaseURL: 'https://g4metalab-default-rtdb.firebaseio.com',
    storageBucket: 'g4metalab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjd5c7f7HlnJca-VbdgUQrX901eNuxIB0',
    appId: '1:61999112245:ios:fcb3217c4c0c1dba31117c',
    messagingSenderId: '61999112245',
    projectId: 'g4metalab',
    databaseURL: 'https://g4metalab-default-rtdb.firebaseio.com',
    storageBucket: 'g4metalab.appspot.com',
    androidClientId: '61999112245-1js8pkvkb7pk8tesn8gdf35t12dliijj.apps.googleusercontent.com',
    iosClientId: '61999112245-i2nfi6stis7r20ru3ahcir1mem8mh2mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.nxlMachineTest',
  );
}
